apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: us-central1-docker.pkg.dev/amiable-archive-473111-d4/devops-repo/backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "104.198.225.62"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "YOUR_PASSWORD"
        - name: DB_NAME
          value: "messages_db"
      imagePullSecrets:
      - name: gcp-artifact-registry
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
